// import React from 'react';

// export type Metadata = {
//   title: string;
//   description: string;
// };

// // Crie um contexto com um estado padrão
// export const MetadataContext = React.createContext<Metadata>({
//   title: "PetShop",
//   description: "Generated by create next app",
// });
