// import React, { useState } from 'react';
// import { Metadata, MetadataContext } from '@/contexts/MetadataContext';

// export const MetadataProvider: React.FC = ({ children }) => {
//   const [metadata, setMetadata] = useState<Metadata>({
//     title: "PetShop",
//     description: "Generated by create next app",
//   });



//   return (
//     <MetadataContext.Provider value={{ ...metadata }}>
//       {children}
//     </MetadataContext.Provider>
//   );
// };
